### ISSUE TITLE
주식 정보 사이트 주소

### ISSUE THREAD

**Issue by Taeho24** [Springfield-M1A/Socom_TeamProject#1]

**Comment by Taeho24** [comment]
https://alphasquare.co.kr/home/stock/stock-summary?code=005930&gclid=EAIaIQobChMIqp7no4ej_gIVwNdMAh1O6w17EAAYASAAEgJcuPD_BwE

**Comment by Taeho24** [comment]
https://kr.investing.com/stock-screener/?sp=country::11|sector::a|industry::a|equityType::a|exchange::a%3Ceq_market_cap;1
사이트 이름 : investing.com
일정시간 업데이트 형식
거래량, 시장의 활성도, 변동률, 시가총액 등 확인가능

**Comment by Springfield-M1A** [comment]
개인적인 추천 2
https://m.finance.daum.net/domestic/kospi
사이트 이름 : 다음 금융

위와 동일한 방식
따라서 2개 이상의 사이트에서 비교 응용하고자 할 경우에도 이용 가능
