### ISSUE TITLE
주식 예측 프로그램의 간략화 작업

### ISSUE THREAD

**Issue by Taeho24** [Springfield-M1A/Socom_TeamProject#13]
_Originally posted by @Taeho24 in https://github.com/Springfield-M1A/Socom_TeamProject/issues/7#issuecomment-1520258551_

**Comment by Taeho24** [comment]
프로그램 주식 예측에서 단순히 미래의 주식 값을 예측한 결과 값을 출력할 뿐만 아니라 실제 투자예상 임의의 금액을 변수로 넣었을 때의 손실 값을 같이 출력하면 어떨것 같나요?

**Comment by Taeho24** [comment]
일종의

> 프로그램 주식 예측에서 단순히 미래의 주식 값을 예측한 결과 값을 출력할 뿐만 아니라 실제 투자예상 임의의 금액을 변수로 넣었을 때의 손실 값을 같이 출력하면 어떨것 같나요?

일종의 투자 예측 시뮬레이터인거죠

**Comment by Springfield-M1A** [comment]
응용하면 좋을 것 같네요..
