### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by Springfield-M1A** [Springfield-M1A/Socom_TeamProject#3]
프로젝트 주제 선정을 위한 의견 공유

**Comment by Springfield-M1A** [comment]
## 주식 예측 프로그램

- 주식 시장을 조회, 예측 할 수 있는 프로그램.
- 단순히 주식 정보를 보는 프로그램 뿐만이 아니라, 인공지능 딥러닝 기술을 이용하여 주가의 변동, 매수/매도를 어떻게 하면 좋을 것인지를 예측하는 프로그램을 통해 사용자들로 하여금 조금 더 편하게 다가갈 수 있도록 함
- 예측 한 결과와 실제를 비교, 분석하여 어떤 것이 정확도의 향상을 이끌어 낼 수 있을 지 검토, 보완 가능

**Comment by Taeho24** [comment]
주가의 변동, 매수/매도를 어떻게 하면 좋을 것인지를 예측하는 프로그램을 보여주기 위한 현재 활발한 매수/매도 현황과 거래량을 보여주는 기능도 포함하면 좋을것 같음

**Comment by Taeho24** [comment]
### 현재 거래 시세와 증가/감소 추이를 동시에 그래프 상에 나타남으로 그래프 자체가 복잡함
- 현재 거래 시세의 변동과 증가/감소(주가 저지선)을 나타내는 그래프의 분리를 통한 그래프 단순화
- 과거 그래프 변화 양식에 따른 거래량 비교로 증가/감소 예측 지표 표시

**Comment by Springfield-M1A** [comment]
주식 정보 제공 및 예측 프로그램으로 결정
