### ISSUE TITLE
Chat GPT test 응답 코드가 실행이 안됩니다.

### ISSUE THREAD

**Issue by Taeho24** [Springfield-M1A/Socom_TeamProject#30]
Chat GPT test 응답 코드까지만 작성 완료했습니다.(#27)
초보자 추천 서적을 GPT API를 연결하여 추천해줄 HTML을 작성하겠습니다.

_Originally posted by @Taeho24 in https://github.com/Springfield-M1A/Socom_TeamProject/issues/27#issuecomment-1578654935_
            
HTML실행시 응답화면이 갑자기 사라졌습니다. 이게 서버를 구축한 다음에 해야하는지 코드의 문제인지 모르겠습니다.

**Comment by Springfield-M1A** [comment]
https://github.com/AhnYeonghoo/opensource_project
이거랑 아마 작동방식은 비슷할텐데 참고해보죠

**Comment by Taeho24** [comment]
runserver 실행해서 개발서버 실행 중과 IP주소도 뜨는 것 확인 했습니다.
하지만 실제 IP주소로 검색해서 들어가면 작동이 안되네요.

**Comment by Springfield-M1A** [comment]
완전히 다 지우고 Pull 해서 그대로 했지만 별다른 문제 없네요

**Comment by Taeho24** [comment]
Test GPT API 실행시 응답이 아예 안나오거나 올바르게 안나오는 중입니다.
