### ISSUE TITLE
[참조] 주식 사이트 URL

### ISSUE THREAD

**Issue by Taeho24** [Springfield-M1A/Socom_TeamProject#4]
# 주식 사이트 URL (Search)
- 참조할만한 주식 사이트들을 찾아보자
## URL 참조
- 주식 사이트 URL 정보
- 사이트 이름
- 확인가능 정보 요약
- ...

**Comment by Taeho24** [comment]
https://alphasquare.co.kr/home/stock/stock-summary?code=005930&gclid=EAIaIQobChMIqp7no4ej_gIVwNdMAh1O6w17EAAYASAAEgJcuPD_BwE
사이트 이름 : 알파스퀘어
종목 요약 그래프, 시장정보, 매수 정보등 실시간 확인 사이트

**Comment by Taeho24** [comment]
https://kr.investing.com/stock-screener/?sp=country::11|sector::a|industry::a|equityType::a|exchange::a%3Ceq_market_cap;1
사이트 이름 : investing.com
일정시간 업데이트 형식
거래량, 시장의 활성도, 변동률, 시가총액 등 확인가능

**Comment by Taeho24** [comment]
https://finance.naver.com/
사이트 이름 : 네이버증권
현재 증시 상황, 인기 검색 종목, 활발히 활성되고 있는 종목 실시간 확인 가능

**Comment by Taeho24** [comment]
> [https://kr.investing.com/stock-screener/?sp=country::11|sector::a|industry::a|equityType::a|exchange::a%3Ceq_market_cap;1](https://kr.investing.com/stock-screener/?sp=country::11%7Csector::a%7Cindustry::a%7CequityType::a%7Cexchange::a%3Ceq_market_cap;1) 사이트 이름 : investing.com 일정시간 업데이트 형식 거래량, 시장의 활성도, 변동률, 시가총액 등 확인가능

https://kr.investing.com/charts/stocks-charts
- 실시간 차트를 그래프로 표시
- 특정 지점에 특이사항도 표시되는것 같음

**Comment by Springfield-M1A** [comment]
https://m.stock.naver.com/domestic/index/KOSPI/total
사이트 이름 : 네이버 증권(모바일 버전)
정적 사이트로, 크롤링 할 수 있는 사이트인 것 확인 완료.
KOSPI 부분 종목명 변환으로 용이하게 크롤링 할 수 있음.

**Comment by Springfield-M1A** [comment]
https://m.finance.daum.net/domestic/kospi
사이트 이름 : 다음 금융
위와 동일한 방식따라서 2개 이상의 사이트에서 비교 응용하고자 할 경우에도 이용 가능

**Comment by Springfield-M1A** [comment]
추가로 라벨이 알맞게 설정되면 좋을 것 같습니다.
Discussion 라벨 사용이 좋지 않을까 싶으며, 필요한 라벨이 있다면 문의해주시면 추가하겠습니다

**Comment by Taeho24** [comment]
> 추가로 라벨이 알맞게 설정되면 좋을 것 같습니다. Discussion 라벨 사용이 좋지 않을까 싶으며, 필요한 라벨이 있다면 문의해주시면 추가하겠습니다

확인했습니다.
