### ISSUE TITLE
기말발표

### ISSUE THREAD

**Issue by Springfield-M1A** [Springfield-M1A/Socom_TeamProject#44]

**Comment by Taeho24** [comment]
발표자료는 제가 만들겠습니다.

**Comment by Taeho24** [comment]
index 내용으로는 중간 발표내용을 참고해서 주제 선정 이유와 내용을 상대적으로 짧게 하고 프로그램의 순기능과 기능과 관련된 이슈 & 해결 방법,  프로그램 동작 시연과 개선방안을 중심으로 하면 좋을 것 같습니다

**Comment by Springfield-M1A** [comment]
저 친구 PPT 만들라 시키고 발표를 하시는게 나을 것 같네요

**Comment by Taeho24** [comment]
개선 방안과 관련해서는 제가 최근까지 시도해 보던 Chat GTP API와 관련해서 이야기 하면 좋을 것 같아요
HTML로 API를 작성해보려고 했는데 open_api-keys에서 충동이 나던지 코드의 오류인지 응답을 안했습니다.
일단 테스트 코드만 완성 시켰는데 원활한 작동이 불가했다는 내용의 추가는 어떤가요?

**Comment by Springfield-M1A** [comment]
ChatGPT API 뭐 시간 남았는데 한번 해보고, 그런 얘기 발표자료에 넣으면 되죠

또 추가로 입력 출력에 따른거라든가, 그런거 다 고려해서 만들어놨으니까
정규화 기능, 코스피/코스닥과 상관계수를 이용한 분석기능, ARIMA 모델을 이용한 5일동안의 주가 예측 등 구현 나름 해놨고 README에도 써놨으니까
직접 한번 클론해서 해보고, PPT만들라시켜서 발표하죠

근데 추가로 GPT API KEYS가 충돌이 난거는 API 값을 넣어야 사용이가능한데  안넣어서 그렇게 오류가 생긴거 아닐까요
