### ISSUE TITLE
GUI HTML 설정 & 관련 브랜치 생성

### ISSUE THREAD

**Issue by Taeho24** [Springfield-M1A/Socom_TeamProject#5]
Feature_testing_list 브랜치를 만들어 테스트 웹크롤링 작업부터 시작하고, 이후 HTML 작업 실시하겠습니다.

**Comment by Springfield-M1A** [comment]
프로젝트 내 파일이 몰리는 상황을 방지하기 위해 구분을 하기 위해 메인 브랜치를 조금 변경했습니다.
Pull 하여 업데이트 한 후 진행하면 좋을 것 같아요

**Comment by Taeho24** [comment]
investing.com(인베스팅닷컴) Ajax를 이용한 정보수집 불가 (import requests, BeautifuSoup)
인베스팅닷컴이 Cloudflare을 도입하면서 수집 방법들 저지 중으로 생각됨
Cloudflare로 'reauests' 라이브러리 사용하는 것조차도 막음
