### ISSUE TITLE
구현하면 좋을 기능 API

### ISSUE THREAD

**Issue by Springfield-M1A** [Springfield-M1A/Socom_TeamProject#7]
최종으로는 웹 브라우저에 https://m.stock.naver.com/ 와 같은 사이트처럼 정보제공을 하는 페이지를 만들게 될 텐데
이 때, 어떤 기능들이 있으면 좋을 지에 대해서

# 현재 구상안
- 사이트 안내 (index.html)
- 사이트 진입 전, 필수프로그램 설치 안내 창(BeautifulSoap, ...) 등을 다른 유저들도 자동으로 설치할 수 있도록
- 대표적인 종목 몇 개 메인 화면 우선 노출
- 즐겨찾기 해 둔 종목
- 특정 종목 검색

**Comment by Taeho24** [comment]
다른 예측 프로그램들 보면 보여주는 항목이 너무 많아서 전문가가 아니면 오히려 혼란이 올 수 있을 것 같아요.
전문가들은 주가 실시간 사이트를 분석하거나 다른 이용 가능한 예측 사이트들이 많으니 저희는 오히려 주식 입문자용 같은 느낌으로 간략화 시키는 것도 하나의 차별성으로 보여줄 수 있고요.

**Comment by Springfield-M1A** [comment]
확실히, 이전 중간발표 자료 준비 때 토의했던 것 처럼, 주식을 잘 모르는 사람들은 주식 프로그램의 복잡한 인터페이스만 봐도 답답할 수 있을 것같다는 생각이 듭니다.
적절하게 디자인을 고려해서 입문자에게 더 친숙하게 간략화하는 것도 매우 좋은 아이디어라고 생각합니다.

**Comment by Springfield-M1A** [comment]
> 다른 예측 프로그램들 보면 보여주는 항목이 너무 많아서 전문가가 아니면 오히려 혼란이 올 수 있을 것 같아요. 전문가들은 주가 실시간 사이트를 분석하거나 다른 이용 가능한 예측 사이트들이 많으니 저희는 오히려 주식 입문자용 같은 느낌으로 간략화 시키는 것도 하나의 차별성으로 보여줄 수 있고요.


확실히, 이전 중간발표 자료 준비 때 토의했던 것 처럼, 주식을 잘 모르는 사람들은 주식 프로그램의 복잡한 인터페이스만 봐도 답답할 수 있을 것같다는 생각이 듭니다.
적절하게 디자인을 고려해서 입문자에게 더 친숙하게 간략화하는 것도 매우 좋은 아이디어라고 생각합니다.
